version: 2

jobs:
  build:
    machine:
      image: ubuntu-2204:2024.04.4
    resource_class: medium
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build and push Docker Image to DockerHub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker buildx create --name armbuilder
            docker buildx use armbuilder
            docker buildx build --platform linux/amd64,linux/arm64 -t hablijack/greenhouse-frontend-nuxt3:1.15.5 --push .

workflows:
  version: 2
  qualitygate_and_build:
    jobs:
      - build
