version: 2

jobs:
  build:
    machine:
      image: ubuntu-2004:2022.10.1
    resource_class: medium
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build and push Docker Image to DockerHub
          command: |
            docker build -t hablijack/greenhouse-frontend-nuxt3:1.7.2 .
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push hablijack/greenhouse-frontend-nuxt3:1.7.2
workflows:
  version: 2
  qualitygate_and_build:
    jobs:
      - build
